<div class="row-align-items-center ">
					<div class="col-4">
						<div class="d-grid gap-2">
							<a href="restaurante.php" class="btn btn-outline-secondary">Categorias</a>
						</div>
						<br>
					</div>
				</div>


				<div class="row-align-items-center ">
					<div class="col-4">
						<div class="d-grid gap-2">
							<a href="Produtos.php" class="btn btn-outline-secondary">Produtos</a>
						</div>
						<br>
					</div>
				</div>


				<div class="row-align-items-center">
					<div class="col-4">
						<div class="d-grid gap-2">
							<a href="Usuarios.php" class="btn btn-outline-secondary">Usuarios</a>
						</div>
						<br>
					</div>
				</div>


				<div class="row-align-items-center">
					<div class="col-4">
						<div class="d-grid gap-2">
							<a href="Relatórios.php" class="btn btn-outline-secondary">Relatorios</a>
						</div>
						<br>
					</div>
				</div>

				<div class="row-align-items-center">
					<div class="col-4">
						<div class="d-grid gap-2">
							<a href="atendente.php" class="btn btn-outline-secondary">Atendente</a>
						</div>
						<br>
					</div>
				</div>